name: Deploy to Elastic Beanstalk (AWS Free Tier)

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3

    - name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '17'
        cache: 'maven'

    - name: Build with Maven
      run: chmod +x mvnw && ./mvnw clean package -DskipTests

    - name: Inject Secure AWS Environment Variables
      run: |
        mkdir -p .ebextensions
        cat <<EOT >> .ebextensions/01_env.config
        option_settings:
          aws:elasticbeanstalk:application:environment:
            PORT: 5000
            DB_URL: \${{ secrets.DB_URL }}
            DB_USER: postgres
            DB_PASSWORD: \${{ secrets.DB_PASSWORD }}
            AWS_ACCESS_KEY_ID: \${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: \${{ secrets.AWS_SECRET_ACCESS_KEY }}
        EOT

    - name: Create Deployment Artifact (ZIP)
      run: zip -r deploy.zip Procfile .ebextensions target/ecommerce-extension-0.0.1-SNAPSHOT.jar

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ecommerce-api
        environment_name: ecommerce-api-env
        version_label: ${{ github.sha }}
        region: us-east-1
        deployment_package: deploy.zip
